# Generated by Django 3.2 on 2022-03-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiid_india_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
