# Generated by Django 3.2 on 2022-04-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiid_india_pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
