# Generated by Django 3.2 on 2022-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiid_india_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='page',
            field=models.CharField(choices=[('About', 'About'), ('Objectives', 'Objectives'), ('Programmes', 'Programmes')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
