# Generated by Django 3.2 on 2022-04-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiid_india_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
