# Generated by Django 3.2 on 2022-03-29 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiid_india_pages', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewslettersAndReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(upload_to='files/reports/')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiid_india_pages.newslettersandreports')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter', models.FileField(upload_to='files/newsletter/')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiid_india_pages.newslettersandreports')),
            ],
        ),
    ]
