# Generated by Django 3.2 on 2022-03-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiid_india_pages', '0002_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=600)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
