# Generated by Django 3.2 on 2022-03-28 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiid_india_pages', '0003_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to='images/carousel/'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/pages/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiid_india_pages.page')),
            ],
        ),
    ]
