# Generated by Django 3.2 on 2022-03-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiid_india_pages', '0004_subscriber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
